name: bitkub_test
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.1
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^9.2.4
  get_it: ^8.2.0
  go_router: ^16.2.4
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  analyzer: ^7.7.0
  bloc_test: ^10.0.0
  build_runner: ^2.6.0
  json_serializable: ^6.11.1
  mockito: ^5.5.0

flutter:
  uses-material-design: true
